import { useState } from 'react'
import Head from 'next/head'
import { Manrope } from 'next/font/google'
import { Button, TextDisplay } from '@/components'

const manrope = Manrope({ subsets: ['latin'] })

export default function Home() {
  const [ gameHasStarted, setGameHasStarted ] = useState<boolean>(false)
  return (
    <>
      <Head>
        <title>Shake It Like a Cheese Stick</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={manrope.className}>
      <Button onClick={() => setGameHasStarted(!gameHasStarted)}>
        { gameHasStarted ? 'Stop the dance' : 'Begin the dance' }
      </Button>
        <TextDisplay isActive={gameHasStarted} />
      </main>
    </>
  )
}
